name: fantasytask
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.1
  hooks_riverpod: ^0.14.0+5
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/official_pp.jpg

  fonts:
    - family: YellowTail
      fonts:
        - asset: fonts/YellowTail/Yellowtail-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
